### ISSUE TITLE
Handling Complex Scenarios

### ISSUE THREAD

**Issue by satyajit-behera** [mauroservienti/Composite-UI-Sample#1]
Hi,

Was just looking at how do I handle the composite UI in a complex scenario where the record in the demo has to be displayed as a collection of customers in a repeater control. How do I link the customer id with the order id when it is a collection of customers linked to their corresponding orders.

Please leave some note also regarding the directive and how it is achieving the composite ui principle.

Also, how do we handle POST and PUT scenarios within a composite UI.

Thanks a lot for this excellent piece of work.

**Comment by mauroservienti** [comment]
@satyajit-behera chime in also here https://groups.google.com/d/msgid/particularsoftware/CAL6donuj-mtTDsfccxDcUXh1auWhx45uTZBKPuw316pgbPSYLA%40mail.gmail.com?utm_medium=email&utm_source=footer

**Comment by satyajit-behera** [comment]
This video from Udi is inspiring.
https://www.youtube.com/watch?v=eNO0dVYEYZk

Thanks

**Comment by mauroservienti** [comment]
List composition is available at https://github.com/mauroservienti/designing-a-ui-for-microservices-demos
Closing.
